Support Gitlab image names (with forward slashes in the container name).
emk/compose_yml pull request #13
Opened 2017-12-28 15:31 UTC by khuey

Gitlab's private container registry allows (and even encourages you to use) slashes in the container name.

e.g.
`registry.gitlab.com/org-name/repo-name/optional-name/optional-image-name:tag`

This changes the `IMAGE` regex to allow forward slashes in the container name (match group 4).

2017-12-28 16:46 UTC, emk requested changes
Interesting!

As I've mentioned before, `compose_yml` tries very hard to adhere to the relevant Docker standards, and most changes like this will typically require a pointer to the relevant documentation. Is this an officially valid container name, according to Docker? (The last time I looked, I seem to remember that it wasn't.) If this is a non-standard extension, has anybody specified it anywhere?

Also, there are no tests included with this patch.

2017-12-30 15:45 UTC, khuey commented
See https://github.com/docker/distribution/blob/master/reference/reference.go, particularly

```//	name                            := [domain '/'] path-component ['/' path-component]*```

There's at least one path component but there can be an unbounded number of them.

2017-12-30 22:40 UTC, emk commented
> See https://github.com/docker/distribution/blob/master/reference/reference.go, particularly

Ah, that's perfect! I'll merge this when I get back to coding next week. Feel free to ping me Wednesday if I haven't released it.

2020-02-02 16:43 UTC, merged

2020-02-02 16:44 UTC, emk commented
Oh, wow, this slipped through the cracks years ago, and I just noticed it doing issue triage now. :-( My apologies, and very belated thanks for the patch and the docs!

2020-02-02 16:53 UTC, khuey commented
No worries, I figured you'd just stopped maintaining this.

2020-02-02 17:34 UTC, emk commented
Actually, it has at least one serious production user. So if something actually breaks, it tends to get fixed quickly. But the maintenance is purely passive for now, because it usually just keeps working.

I try to merge pull requests when I see them, but if they get lost at the bottom of pile of other PRs, it can take me a long time to find them again. :-(